### ISSUE TITLE
Provide emotes from the meta discord

### ISSUE THREAD

**Issue by Earu** [Metastruct/node-metaconcord#3]
The old system (metaluvit) provided an access to a list of the discord emotes which made them usable in-game, it was located there: **http://g2.metastruct.net:20122/discord/guild/emojis**, now that metaluvit has been replaced it'd be good if you could re-implement that.

The format of the file was just a huge json list of the urls pointing to each emote image. The client-side implementation of this can be found here: **https://gitlab.com/metastruct/internal/srvaddons/-/blob/master/Chat/lua/easychat/modules/client/discord_emoticons.lua#L16**

**Comment by Tenrys** [comment]
This is already a thing. But it looks like the URL for it is returning an SSL protocol error for some reason, and it looks like the Discord bot used disconnects at random times?

**Comment by Tenrys** [comment]
Anyways, it's always been at available at the URL you used previously. I don't think it should become unavailable again either unless Discord crashes momentarily.

**Comment by Earu** [comment]
Is it available now then?

**Comment by Tenrys** [comment]
![image](https://user-images.githubusercontent.com/3979239/93490344-a61a0880-f908-11ea-8020-f6d0b3447101.png)

Yes

**Comment by Zeni44** [comment]
![image](https://user-images.githubusercontent.com/11852198/93490443-c5189a80-f908-11ea-9166-c09113a85ce6.png)
